[DEV-3656]: Bump dependencies. Support python3.12. Publish package to our Code Artifacts (#16)
* [DEV-3656]: Bump dependencies. Support python3.12. Publish package to code artifacts.

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -30,6 +30,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           persist-credentials: false
+          fetch-depth: 0
       - name: Get release version
         id: get_release_version
         run: |
@@ -53,13 +54,17 @@ jobs:
         run: |
           if [[ -n "${{ inputs.highest_semver_tag }}" ]]; then
             echo "Using provided highest semver version: ${{ inputs.highest_semver_tag }}"
-            echo "::set-output name=highest_semver_tag::${{ inputs.highest_semver_tag }}"
+            echo "highest_semver_tag=${{ inputs.highest_semver_tag }}" >> $GITHUB_OUTPUT
           else
             echo "No release version provided. Falling back to infra/scripts/setup-common-functions.sh."
             source infra/scripts/setup-common-functions.sh
-            SEMVER_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$'
-            if echo "${RELEASE_VERSION}" | grep -P "$SEMVER_REGEX" &>/dev/null ; then
-              echo ::set-output name=highest_semver_tag::$(get_tag_release -m)
+            SEMVER_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+\+zing\.\d+$'
+            if echo "${RELEASE_VERSION}" | grep -P "$SEMVER_REGEX" &>/dev/null; then
+              echo "Matched strict zing tag: ${RELEASE_VERSION}"
+              echo "highest_semver_tag=$(get_tag_release -m)" >> $GITHUB_OUTPUT
+            else
+              echo "Error: Tag ${RELEASE_VERSION} does not match the required format (e.g., v0.42.0+zing.1)."
+              exit 1
             fi
           fi
       - name: Check output
@@ -81,19 +86,19 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.11"
+          python-version: "3.12"
           architecture: x64
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version-file: './ui/.nvmrc'
           registry-url: 'https://registry.npmjs.org'
-      - name: Build UI
-        run: make build-ui
       - name: Build wheels
         run: |
           python -m pip install build
           python -m build --wheel --outdir wheelhouse/
+      - name: Build UI
+        run: make build-ui
       - uses: actions/upload-artifact@v4
         with:
           name: python-wheels
@@ -108,7 +113,7 @@ jobs:
         id: setup-python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.11"
+          python-version: "3.12"
           architecture: x64
       - name: Setup Node
         uses: actions/setup-node@v3
@@ -119,13 +124,13 @@ jobs:
         # There's a `git restore` in here because `make install-go-ci-dependencies` is actually messing up go.mod & go.sum.
         run: |
           pip install -U pip setuptools wheel twine
-          make build-ui
           git status
           git restore go.mod go.sum
           git restore sdk/python/feast/ui/yarn.lock
       - name: Build
         run: |
-          python3 setup.py sdist
+          python -m build --sdist --outdir dist/
+          make build-ui
       - uses: actions/upload-artifact@v4
         with:
           name: source-distribution
@@ -143,9 +148,9 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
+        uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
       - name: Build image
         run: |
           make build-${{ matrix.component }}-docker REGISTRY=${REGISTRY} VERSION=${VERSION_WITHOUT_PREFIX}
@@ -158,7 +163,7 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest,  macos-13 ]
-        python-version: ["3.9", "3.10", "3.11"]
+        python-version: ["3.9", "3.10", "3.11", "3.12"]
         from-source: [ True, False ]
     env:
       # this script is for testing servers
@@ -181,7 +186,7 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
-      - uses: actions/download-artifact@v4.1.7
+      - uses: actions/download-artifact@v3
         with:
           name: python-wheels
           path: dist
