chore: Adding exceptiong handling to build_wheels and additional logging
Signed-off-by: Francisco Javier Arceo <farceo@redhat.com>

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -206,11 +206,15 @@ jobs:
       # Validate that the feast version installed is not development and is the correct version of the tag we ran it off of.
       - name: Validate Feast Version
         run: |
+          if ! VERSION_OUTPUT=$(feast version); then
+            echo "Error: Failed to get Feast version."
+            exit 1
+          fi
           VERSION_REGEX='[0-9]+\.[0-9]+\.[0-9]+'
           OUTPUT_REGEX='^Feast SDK Version: "$VERSION_REGEX"$'
-          VERSION_OUTPUT=$(feast version)
           VERSION=$(echo $VERSION_OUTPUT | grep -oE "$VERSION_REGEX")
           OUTPUT=$(echo $VERSION_OUTPUT | grep -E "$REGEX")
+          echo "Installed Feast Version: $VERSION and using Feast Version: $VERSION_WITHOUT_PREFIX"
           if  [ -n "$OUTPUT" ] && [ "$VERSION" = "$VERSION_WITHOUT_PREFIX" ]; then
             echo "Correct Feast Version Installed"
           else
