chore: Fixing typo in publish workflow
Signed-off-by: Francisco Javier Arceo <farceo@redhat.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -31,30 +31,16 @@ jobs:
       highest_semver_tag: ${{ steps.get_highest_semver.outputs.highest_semver_tag }}
     steps:
       - uses: actions/checkout@v4
-      - name: Validate custom version input
-        id: validate_custom_version
-        run: |
-          if [[ -n "${{ github.event.inputs.custom_version }}" ]]; then
-            VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
-            if [[ ! "${{ github.event.inputs.custom_version }}" =~ $VERSION_REGEX ]]; then
-              echo "Error: custom_version must match semantic versioning (e.g., v1.2.3)."
-              exit 1
-            fi
-            echo "Validated custom version: ${{ github.event.inputs.custom_version }}"
-          fi
-      - name: Strip 'v' Prefix for Highest SemVer Tag
-        id: strip_prefix
-        run: |
-          HIGHEST_SEMVER_TAG="${{ github.event.inputs.custom_version#v }}"
-          echo "::set-output name=highest_semver_tag::$HIGHEST_SEMVER_TAG"
-          echo "Highest SemVer Tag: $HIGHEST_SEMVER_TAG"
-          
-
       - name: Get release version
         id: get_release_version
         run: |
           if [[ -n "${{ github.event.inputs.custom_version }}" ]]; then
+            VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
             echo "Using custom version: ${{ github.event.inputs.custom_version }}"
+            if [[ ! "${{ github.event.inputs.custom_version }}" =~ $VERSION_REGEX ]]; then
+              echo "Error: custom_version must match semantic versioning (e.g., v1.2.3)."
+              exit 1
+            fi
             echo "::set-output name=release_version::${{ github.event.inputs.custom_version }}"
           elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
             echo "Using tag reference: ${GITHUB_REF#refs/tags/}"
